HAI 1.4

CAN HAS STDIO?

I HAS A readFile ITZ I IZ STDIO'Z OPEN YR "key" AN YR "r" MKAY
I IZ STDIO'Z DIAF YR readFile MKAY
I HAS A contents ITZ I IZ STDIO'Z LUK YR readFile AN YR 1024 MKAY
VISIBLE contents
I IZ STDIO'Z CLOSE YR readFile MKAY

KTHXBYE
